<?php
declare(strict_types=1);
return [
    // Public navigation
    'nav.inicio'           => 'Home',
    'nav.como_funciona'    => 'How It Works',
    'nav.para_clientes'    => 'For Clients',
    'nav.para_parceiros'   => 'For Partners',
    'nav.vetriks'          => 'Vetriks',
    'nav.sobre'            => 'About',
    'nav.contato'          => 'Contact',
    'nav.entrar'           => 'Sign In',
    'nav.fale_conosco'     => 'Contact Us',
    'nav.abrir_demanda'    => 'Submit Request',

    // Hero
    'hero.label'           => 'Strategic Construction Structuring',
    'hero.title'           => 'The brokerage that <em>simplifies</em> what is complex.',
    'hero.body'            => 'We connect clients to a qualified network of partners for construction and renovation — with method, agility and full transparency.',
    'hero.cta_primary'     => 'Discover Lexus',
    'hero.cta_secondary'   => 'How it works',
    'hero.stat_empresas'   => 'Partner Companies',
    'hero.stat_prestadores'=> 'Service Providers',
    'hero.scroll'          => 'Scroll',

    // About
    'sobre.label'          => 'About Lexus',
    'sobre.title'          => 'A new way to <em>structure</em> construction.',
    'sobre.p1'             => 'Lexus specializes in <strong>structuring, connecting and selecting partners</strong> for construction and renovation. We act as a strategic broker between clients and executing companies — making a complex process simpler, faster and more efficient.',
    'sobre.p2'             => 'Our proprietary methodology organizes client demand in a clear and targeted way, <strong>facilitating communication with the market</strong> and increasing the accuracy of received proposals.',
    'sobre.p3'             => 'We collect multiple quotes whenever possible, allowing objective comparison between quality, timeline and investment. Lexus does not execute construction — our role is to <strong>structure, present and assist in selecting the best options.</strong>',
    'sobre.pill'           => '✦ B2B Model — No upfront charges',

    // Methodology
    'metodo.label'         => 'Methodology',
    'metodo.title'         => 'How we work',
    'metodo.intro'         => 'A structured process to reduce risks and ensure clarity at every stage of your project.',
    'metodo.step1_title'   => 'Demand Structuring',
    'metodo.step1_desc'    => 'We organize client needs clearly and objectively, mapping scope, priorities and expectations before any market contact.',
    'metodo.step2_title'   => 'Qualified Connection',
    'metodo.step2_desc'    => 'We connect the client to a validated network of professionals with the Vetriks Seal — eliminating isolated searches and reducing risks from the start.',
    'metodo.step3_title'   => 'Quote Collection',
    'metodo.step3_desc'    => 'We gather multiple proposals for objective comparison between quality, timeline and investment — with full clarity for the client.',
    'metodo.step4_title'   => 'Decision Support',
    'metodo.step4_desc'    => 'We assist in analyzing and selecting the best option. Negotiation occurs directly between client and contractor, ensuring full transparency.',

    // Vetriks
    'vetriks.label'        => 'Exclusive Certification',
    'vetriks.title'        => '<em>Vetriks</em> Seal',
    'vetriks.desc'         => 'All Lexus partners undergo a rigorous qualification process. The Vetriks Seal certifies experience, execution capacity and reliability.',
    'vetriks.seal'         => 'Vetriks Certified Partners',
    'vetriks.crit_label'   => 'Qualification Criteria',
    'vetriks.crit1_title'  => 'Proven Experience',
    'vetriks.crit1_desc'   => 'Track record of completed projects, with verified references and portfolio analyzed by the Lexus team.',
    'vetriks.crit2_title'  => 'Execution Capacity',
    'vetriks.crit2_desc'   => 'Assessment of operational structure, technical team and capacity to handle the demanded project scope.',
    'vetriks.crit3_title'  => 'Reliability',
    'vetriks.crit3_desc'   => 'Reputation analysis, deadline compliance and contractual commitment with previous clients.',

    // Model
    'modelo.label'         => 'Business Model',
    'modelo.title'         => 'What makes Lexus <em>different</em>',
    'modelo.card1_title'   => 'No Financial Intermediation',
    'modelo.card1_desc'    => 'The entire commercial process occurs directly between client and contractor. Lexus never intermediates payments — full transparency is non-negotiable.',
    'modelo.card2_title'   => 'No Upfront Charges',
    'modelo.card2_desc'    => 'Our B2B model requires no advance payment. The client accesses the qualified network and methodology without any initial financial risk.',
    'modelo.card3_title'   => 'Execution Flexibility',
    'modelo.card3_desc'    => 'We work on complete projects or by stages, always adapting the process to each client\'s reality and specific priorities.',

    // CTA
    'cta.label'            => 'Next Step',
    'cta.title'            => 'Ready to make <em>better decisions</em> on your project?',
    'cta.body'             => 'Talk to Lexus and discover how our qualified network and exclusive methodology transform your project.',
    'cta.btn_contato'      => 'Get in Touch',
    'cta.btn_saiba'        => 'Learn More',

    // Footer
    'footer.copyright'     => '© :ano Lexus — Strategic Construction Structuring',
    'footer.termos'        => 'Terms',
    'footer.privacidade'   => 'Privacy',
    'footer.status'        => 'Status',

    // General
    'geral.salvar'         => 'Save',
    'geral.cancelar'       => 'Cancel',
    'geral.editar'         => 'Edit',
    'geral.excluir'        => 'Delete',
    'geral.voltar'         => 'Back',
    'geral.buscar'         => 'Search',
    'geral.filtrar'        => 'Filter',
    'geral.limpar'         => 'Clear',
    'geral.enviar'         => 'Submit',
    'geral.confirmar'      => 'Confirm',
    'geral.sim'            => 'Yes',
    'geral.nao'            => 'No',
    'geral.ativo'          => 'Active',
    'geral.inativo'        => 'Inactive',
    'geral.acoes'          => 'Actions',
    'geral.detalhes'       => 'Details',
    'geral.visualizar'     => 'View',
    'geral.criar'          => 'Create',
    'geral.novo'           => 'New',
    'geral.anterior'       => 'Previous',
    'geral.proximo'        => 'Next',
    'geral.carregando'     => 'Loading...',
    'geral.nenhum_registro'=> 'No records found.',
    'geral.sucesso'        => 'Operation completed successfully.',
    'geral.erro_generico'  => 'An error occurred. Please try again.',
    'geral.obrigatorio'    => 'This field is required.',
    'geral.email_invalido' => 'Invalid email.',
    'geral.todos'          => 'All',
    'geral.exportar'       => 'Export',
    'geral.importar'       => 'Import',
    'geral.de'             => 'of',
    'geral.ate'            => 'to',
    'geral.registros'      => 'records',
    'geral.pagina'         => 'Page',

    // Auth
    'auth.entrar'              => 'Sign In',
    'auth.sair'                => 'Sign Out',
    'auth.criar_conta'         => 'Create Account',
    'auth.esqueci_senha'       => 'Forgot password',
    'auth.redefinir_senha'     => 'Reset Password',
    'auth.email'               => 'Email',
    'auth.senha'               => 'Password',
    'auth.confirmar_senha'     => 'Confirm Password',
    'auth.nome'                => 'Full name',
    'auth.lembrar'             => 'Remember me',
    'auth.login_sucesso'       => 'Login successful.',
    'auth.login_falha'         => 'Invalid email or password.',
    'auth.logout_sucesso'      => 'You have been signed out.',
    'auth.conta_inativa'       => 'Your account is inactive. Please contact support.',
    'auth.token_invalido'      => 'Invalid or expired token.',
    'auth.senha_redefinida'    => 'Password reset successfully.',
    'auth.email_enviado'       => 'Reset email sent.',
    'auth.2fa_titulo'          => 'Two-Factor Authentication',
    'auth.2fa_codigo'          => 'Verification code',
    'auth.2fa_invalido'        => 'Invalid code.',
    'auth.primeiro_acesso'     => 'First Access',
    'auth.criar_superadmin'    => 'Create Super Administrator',

    // Sidebar Team
    'sidebar.dashboard'        => 'Dashboard',
    'sidebar.clientes'         => 'Clients',
    'sidebar.parceiros'        => 'Partners',
    'sidebar.demandas'         => 'Demands',
    'sidebar.oportunidades'    => 'Opportunities',
    'sidebar.propostas'        => 'Proposals',
    'sidebar.contratos'        => 'Contracts',
    'sidebar.comissoes'        => 'Commissions',
    'sidebar.qualificacao'     => 'Qualification',
    'sidebar.vetriks'          => 'Vetriks',
    'sidebar.crm'              => 'CRM',
    'sidebar.tarefas'          => 'Tasks',
    'sidebar.mensagens'        => 'Messages',
    'sidebar.relatorios'       => 'Reports',
    'sidebar.configuracoes'    => 'Settings',
    'sidebar.usuarios'         => 'Users',
    'sidebar.permissoes'       => 'Permissions',
    'sidebar.logs'             => 'Logs',
    'sidebar.jobs'             => 'Jobs',
    'sidebar.minha_conta'      => 'My Account',

    // Sidebar Client
    'sidebar_cli.dashboard'    => 'Dashboard',
    'sidebar_cli.demandas'     => 'My Demands',
    'sidebar_cli.propostas'    => 'Received Proposals',
    'sidebar_cli.mensagens'    => 'Messages',
    'sidebar_cli.minha_conta'  => 'My Account',

    // Sidebar Partner
    'sidebar_par.dashboard'    => 'Dashboard',
    'sidebar_par.oportunidades'=> 'Opportunities',
    'sidebar_par.propostas'    => 'My Proposals',
    'sidebar_par.comissoes'    => 'Commissions',
    'sidebar_par.perfil'       => 'My Profile',
    'sidebar_par.mensagens'    => 'Messages',
    'sidebar_par.minha_conta'  => 'My Account',

    // Demand Status
    'status.novo'                  => 'New',
    'status.em_triagem'            => 'In Triage',
    'status.em_estruturacao'       => 'Structuring',
    'status.pronto_repasse'        => 'Ready for Referral',
    'status.distribuido'           => 'Distributed',
    'status.aguardando_respostas'  => 'Awaiting Responses',
    'status.recebendo_propostas'   => 'Receiving Proposals',
    'status.em_curadoria'          => 'In Curation',
    'status.apresentado_cliente'   => 'Presented to Client',
    'status.em_negociacao'         => 'In Negotiation',
    'status.contrato_formalizacao' => 'Contract Formalization',
    'status.fechado_ganho'         => 'Closed — Won',
    'status.fechado_perda'         => 'Closed — Lost',
    'status.pausado'               => 'Paused',
    'status.cancelado'             => 'Cancelled',

    // Partner Status
    'status_par.cadastrado'        => 'Registered',
    'status_par.pendente_analise'  => 'Pending Review',
    'status_par.em_qualificacao'   => 'In Qualification',
    'status_par.aprovado'          => 'Approved',
    'status_par.vetriks_ativo'     => 'Vetriks Active',
    'status_par.reprovado'         => 'Rejected',
    'status_par.suspenso'          => 'Suspended',
    'status_par.inativo'           => 'Inactive',

    // Proposal Status
    'status_prop.rascunho'         => 'Draft',
    'status_prop.enviada'          => 'Submitted',
    'status_prop.em_analise'       => 'Under Review',
    'status_prop.shortlist'        => 'Shortlisted',
    'status_prop.descartada'       => 'Discarded',
    'status_prop.selecionada'      => 'Selected',
    'status_prop.convertida'       => 'Converted',
    'status_prop.perdida'          => 'Lost',

    // Commission Status
    'status_com.prevista'              => 'Expected',
    'status_com.aguardando_confirmacao'=> 'Awaiting Confirmation',
    'status_com.confirmada'            => 'Confirmed',
    'status_com.faturada'              => 'Invoiced',
    'status_com.recebida'              => 'Received',
    'status_com.atrasada'              => 'Overdue',
    'status_com.cancelada'             => 'Cancelled',

    // Errors
    'erro.pagina_nao_encontrada' => 'Page not found.',
    'erro.sem_permissao'         => 'You do not have permission to access this resource.',
    'erro.interno'               => 'Internal server error.',
    'erro.csrf'                  => 'Invalid security token. Please reload the page.',
    'erro.rate_limit'            => 'Too many requests. Please try again shortly.',
    'erro.validacao'             => 'Please check the fields and try again.',

    // Contact
    'contato.titulo'       => 'Get in Touch',
    'contato.nome'         => 'Your name',
    'contato.email'        => 'Your email',
    'contato.telefone'     => 'Phone',
    'contato.assunto'      => 'Subject',
    'contato.mensagem'     => 'Message',
    'contato.enviar'       => 'Send Message',
    'contato.sucesso'      => 'Message sent successfully. We will get back to you soon.',

    // Demand Form
    'demanda.titulo'           => 'Submit Request',
    'demanda.dados_pessoais'   => 'Personal Information',
    'demanda.dados_obra'       => 'Project Details',
    'demanda.uploads'          => 'Documents and Projects',
    'demanda.revisao'          => 'Review',
    'demanda.tipo_obra'        => 'Project Type',
    'demanda.localizacao'      => 'Location',
    'demanda.metragem'         => 'Area (sqm)',
    'demanda.fase_atual'       => 'Current Phase',
    'demanda.prazo_desejado'   => 'Desired Deadline',
    'demanda.orcamento'        => 'Estimated Budget',
    'demanda.descricao'        => 'Detailed Description',
    'demanda.urgencia'         => 'Urgency',
    'demanda.tem_projeto'      => 'Do you have a project?',
    'demanda.tem_arquiteto'    => 'Do you have an architect?',
    'demanda.multiplas_prop'   => 'Want multiple proposals?',
    'demanda.observacoes'      => 'Additional Notes',
    'demanda.sucesso'          => 'Request submitted successfully. We will contact you soon.',

    // Partner Form
    'parceiro.titulo'          => 'Become a Partner',
    'parceiro.dados_empresa'   => 'Company Information',
    'parceiro.dados_prof'      => 'Professional Details',
    'parceiro.qualificacao'    => 'Qualification',
    'parceiro.tipo'            => 'Partner Type',
    'parceiro.especialidades'  => 'Specialties',
    'parceiro.areas_atuacao'   => 'Service Areas',
    'parceiro.cidades'         => 'Cities Served',
    'parceiro.ticket_medio'    => 'Average Ticket',
    'parceiro.equipe_propria'  => 'Own Team?',
    'parceiro.tempo_mercado'   => 'Years in Market',
    'parceiro.portfolio'       => 'Portfolio',
    'parceiro.certificacoes'   => 'Certifications',
    'parceiro.aceita_repasse'  => 'Accepts referrals?',
    'parceiro.sucesso'         => 'Registration completed. We will review your profile shortly.',

    // Cookies / LGPD
    'cookies.titulo'           => 'Cookie Policy',
    'cookies.mensagem'         => 'We use cookies to improve your experience. By continuing to browse, you agree to our cookie policy.',
    'cookies.aceitar'          => 'Accept All',
    'cookies.rejeitar'         => 'Reject Optional',
    'cookies.configurar'       => 'Configure',
    'cookies.necessarios'      => 'Necessary',
    'cookies.analytics'        => 'Analytics',
    'cookies.marketing'        => 'Marketing',
    'cookies.preferencias'     => 'Preferences',
    'cookies.salvar'           => 'Save Preferences',

    // Chatbot
    'chatbot.titulo'           => 'Hello! How can I help?',
    'chatbot.opcao1'           => 'What is Lexus?',
    'chatbot.opcao2'           => 'How does it work?',
    'chatbot.opcao3'           => 'How to submit a request?',
    'chatbot.opcao4'           => 'How to become a partner?',
    'chatbot.opcao5'           => 'What is the Vetriks Seal?',
    'chatbot.opcao6'           => 'Talk to support',
    'chatbot.voltar'           => 'Back to menu',

    // Dashboard
    'dash.novas_demandas'      => 'New Demands',
    'dash.oportunidades_ativas'=> 'Active Opportunities',
    'dash.propostas_andamento' => 'Proposals in Progress',
    'dash.fechamentos'         => 'Closings',
    'dash.taxa_conversao'      => 'Conversion Rate',
    'dash.parceiros_ativos'    => 'Active Partners',
    'dash.clientes_ativos'     => 'Active Clients',
    'dash.comissoes_previstas' => 'Expected Commissions',
    'dash.comissoes_recebidas' => 'Received Commissions',

    // Institutional pages
    'pagina.como_funciona'     => 'How It Works',
    'pagina.para_clientes'     => 'For Clients',
    'pagina.para_parceiros'    => 'For Partners',
    'pagina.vetriks'           => 'Vetriks Seal',
    'pagina.sobre'             => 'About Lexus',
    'pagina.contato'           => 'Contact',
    'pagina.termos'            => 'Terms of Use',
    'pagina.privacidade'       => 'Privacy Policy',
    'pagina.status'            => 'System Status',
    'pagina.changelog'         => 'Changelog',

    // Settings
    'config.branding'          => 'Branding',
    'config.contatos'          => 'Institutional Contacts',
    'config.smtp'              => 'SMTP Email',
    'config.seo'               => 'SEO',
    'config.lgpd'              => 'LGPD',
    'config.notificacoes'      => 'Notifications',
    'config.matching'          => 'Matching Rules',
    'config.comissao'          => 'Commission Rules',
    'config.distribuicao'      => 'Distribution Rules',
    'config.vetriks_criterios' => 'Vetriks Criteria',
    'config.billing'           => 'Billing',
    'config.stripe'            => 'Stripe',
    'config.asaas'             => 'Asaas',
    'config.webhooks'          => 'Webhooks',
    'config.idioma'            => 'Language & Localization',
    'config.chatbot'           => 'Chatbot',

    // Settings — descriptions
    'config.subtitulo'         => 'Manage all system settings',
    'config.branding_desc'     => 'Logo, name, colors and visual identity',
    'config.smtp_desc'         => 'Email sending configuration',
    'config.seo_desc'          => 'Meta tags, Open Graph and indexing',
    'config.cobranca'          => 'Billing',
    'config.cobranca_desc'     => 'Stripe, Asaas, plans and webhooks',
    'config.notificacoes_desc' => 'Emails, alerts and notification channels',
    'config.integracao'        => 'Integrations',
    'config.integracao_desc'   => 'External APIs and webhooks',
    'config.seguranca'         => 'Security',
    'config.seguranca_desc'    => 'Passwords, 2FA, rate limit and LGPD',
    'config.geral'             => 'General',
    'config.geral_desc'        => 'Language, currency, timezone and preferences',
    'config.legal'             => 'Legal Texts',
    'config.legal_desc'        => 'Terms of use and privacy policy',
    'config.matching_desc'     => 'Matching rules between demands and partners',
    'config.comissao_desc'     => 'Commission percentages and rules',
    'config.vetriks_desc'      => 'Vetriks qualification criteria',
    'config.chatbot_desc'      => 'Chatbot messages and options',

    // My Account (team)
    'conta.titulo'             => 'My Account',
    'conta.dados_pessoais'     => 'Personal Information',
    'conta.alterar_senha'      => 'Change Password',
    'conta.senha_atual'        => 'Current Password',
    'conta.nova_senha'         => 'New Password',
    'conta.confirmar_nova'     => 'Confirm New Password',
    'conta.manter_vazia'       => 'Leave blank to keep current password.',
];
