<?php
declare(strict_types=1);
return [
    // Navegação pública
    'nav.inicio'           => 'Início',
    'nav.como_funciona'    => 'Como Funciona',
    'nav.para_clientes'    => 'Para Clientes',
    'nav.para_parceiros'   => 'Para Parceiros',
    'nav.vetriks'          => 'Vetriks',
    'nav.sobre'            => 'Sobre',
    'nav.contato'          => 'Contato',
    'nav.entrar'           => 'Entrar',
    'nav.fale_conosco'     => 'Fale Conosco',
    'nav.abrir_demanda'    => 'Abrir Demanda',

    // Hero
    'hero.label'           => 'Estruturação Estratégica de Obras',
    'hero.title'           => 'A corretora que <em>simplifica</em> o que é complexo.',
    'hero.body'            => 'Conectamos clientes a uma rede qualificada de parceiros para obras e reformas — com método, agilidade e transparência total.',
    'hero.cta_primary'     => 'Conheça a Lexus',
    'hero.cta_secondary'   => 'Como funciona',
    'hero.stat_empresas'   => 'Empresas Parceiras',
    'hero.stat_prestadores'=> 'Prestadores de Serviço',
    'hero.scroll'          => 'Deslize',

    // Sobre
    'sobre.label'          => 'Sobre a Lexus',
    'sobre.title'          => 'Uma nova forma de <em>estruturar</em> obras.',
    'sobre.p1'             => 'A Lexus é especializada na <strong>estruturação, conexão e seleção de parceiros</strong> para obras e reformas. Atuamos como uma corretora estratégica entre clientes e empresas executoras — tornando um processo complexo mais simples, rápido e eficiente.',
    'sobre.p2'             => 'Nossa metodologia própria organiza a demanda do cliente de forma clara e direcionada, <strong>facilitando a comunicação com o mercado</strong> e aumentando a assertividade nas propostas recebidas.',
    'sobre.p3'             => 'Coletamos múltiplos orçamentos sempre que possível, permitindo comparação objetiva entre qualidade, prazo e investimento. A Lexus não executa obras — nosso papel é <strong>estruturar, apresentar e auxiliar na seleção das melhores opções.</strong>',
    'sobre.pill'           => '✦ Modelo B2B — Sem cobrança antecipada',

    // Metodologia
    'metodo.label'         => 'Metodologia',
    'metodo.title'         => 'Como trabalhamos',
    'metodo.intro'         => 'Um processo estruturado para reduzir riscos e garantir clareza em cada etapa da sua obra.',
    'metodo.step1_title'   => 'Estruturação da Demanda',
    'metodo.step1_desc'    => 'Organizamos as necessidades do cliente de forma clara e objetiva, mapeando escopo, prioridades e expectativas antes de qualquer contato com o mercado.',
    'metodo.step2_title'   => 'Conexão Qualificada',
    'metodo.step2_desc'    => 'Conectamos o cliente a uma rede validada de profissionais com Selo Vetriks — eliminando buscas isoladas e reduzindo riscos desde o início.',
    'metodo.step3_title'   => 'Coleta de Orçamentos',
    'metodo.step3_desc'    => 'Reunimos múltiplas propostas para comparação objetiva entre qualidade, prazo e investimento — com total clareza para o cliente.',
    'metodo.step4_title'   => 'Suporte à Decisão',
    'metodo.step4_desc'    => 'Auxiliamos na análise e seleção da melhor opção. A negociação ocorre diretamente entre cliente e construtora, garantindo transparência total.',

    // Vetriks
    'vetriks.label'        => 'Certificação Exclusiva',
    'vetriks.title'        => 'Selo <em>Vetriks</em>',
    'vetriks.desc'         => 'Todos os parceiros da Lexus passam por um processo rigoroso de qualificação. O Selo Vetriks certifica experiência, capacidade de execução e confiabilidade.',
    'vetriks.seal'         => 'Parceiros Certificados Vetriks',
    'vetriks.crit_label'   => 'Critérios de Qualificação',
    'vetriks.crit1_title'  => 'Experiência Comprovada',
    'vetriks.crit1_desc'   => 'Histórico de projetos realizados, com referências verificadas e portfólio analisado pela equipe Lexus.',
    'vetriks.crit2_title'  => 'Capacidade de Execução',
    'vetriks.crit2_desc'   => 'Avaliação da estrutura operacional, equipe técnica e capacidade para assumir o porte do projeto demandado.',
    'vetriks.crit3_title'  => 'Confiabilidade',
    'vetriks.crit3_desc'   => 'Análise de reputação, cumprimento de prazos e compromisso contratual com clientes anteriores.',

    // Modelo
    'modelo.label'         => 'Modelo de Atuação',
    'modelo.title'         => 'O que torna a Lexus <em>diferente</em>',
    'modelo.card1_title'   => 'Sem Intermediação Financeira',
    'modelo.card1_desc'    => 'Todo o processo comercial ocorre diretamente entre cliente e construtora. A Lexus nunca intermedia pagamentos — transparência total é inegociável.',
    'modelo.card2_title'   => 'Sem Cobrança Antecipada',
    'modelo.card2_desc'    => 'Nosso modelo B2B não exige pagamento adiantado. O cliente acessa a rede qualificada e a metodologia sem nenhum risco financeiro inicial.',
    'modelo.card3_title'   => 'Flexibilidade de Execução',
    'modelo.card3_desc'    => 'Atuamos em obras completas ou por etapas, adaptando sempre o processo à realidade e prioridades específicas de cada cliente.',

    // CTA
    'cta.label'            => 'Próximo Passo',
    'cta.title'            => 'Pronto para tomar <em>decisões melhores</em> na sua obra?',
    'cta.body'             => 'Fale com a Lexus e descubra como nossa rede qualificada e metodologia exclusiva transformam o seu projeto.',
    'cta.btn_contato'      => 'Entrar em Contato',
    'cta.btn_saiba'        => 'Saiba Mais',

    // Footer
    'footer.copyright'     => '© :ano Lexus — Estruturação Estratégica de Obras',
    'footer.termos'        => 'Termos',
    'footer.privacidade'   => 'Privacidade',
    'footer.status'        => 'Status',

    // Geral
    'geral.salvar'         => 'Salvar',
    'geral.cancelar'       => 'Cancelar',
    'geral.editar'         => 'Editar',
    'geral.excluir'        => 'Excluir',
    'geral.voltar'         => 'Voltar',
    'geral.buscar'         => 'Buscar',
    'geral.filtrar'        => 'Filtrar',
    'geral.limpar'         => 'Limpar',
    'geral.enviar'         => 'Enviar',
    'geral.confirmar'      => 'Confirmar',
    'geral.sim'            => 'Sim',
    'geral.nao'            => 'Não',
    'geral.ativo'          => 'Ativo',
    'geral.inativo'        => 'Inativo',
    'geral.acoes'          => 'Ações',
    'geral.detalhes'       => 'Detalhes',
    'geral.visualizar'     => 'Visualizar',
    'geral.criar'          => 'Criar',
    'geral.novo'           => 'Novo',
    'geral.anterior'       => 'Anterior',
    'geral.proximo'        => 'Próximo',
    'geral.carregando'     => 'Carregando...',
    'geral.nenhum_registro'=> 'Nenhum registro encontrado.',
    'geral.sucesso'        => 'Operação realizada com sucesso.',
    'geral.erro_generico'  => 'Ocorreu um erro. Tente novamente.',
    'geral.obrigatorio'    => 'Este campo é obrigatório.',
    'geral.email_invalido' => 'E-mail inválido.',
    'geral.todos'          => 'Todos',
    'geral.exportar'       => 'Exportar',
    'geral.importar'       => 'Importar',
    'geral.de'             => 'de',
    'geral.ate'            => 'até',
    'geral.registros'      => 'registros',
    'geral.pagina'         => 'Página',

    // Auth
    'auth.entrar'              => 'Entrar',
    'auth.sair'                => 'Sair',
    'auth.criar_conta'         => 'Criar Conta',
    'auth.esqueci_senha'       => 'Esqueci minha senha',
    'auth.redefinir_senha'     => 'Redefinir Senha',
    'auth.email'               => 'E-mail',
    'auth.senha'               => 'Senha',
    'auth.confirmar_senha'     => 'Confirmar Senha',
    'auth.nome'                => 'Nome completo',
    'auth.lembrar'             => 'Lembrar de mim',
    'auth.login_sucesso'       => 'Login realizado com sucesso.',
    'auth.login_falha'         => 'E-mail ou senha incorretos.',
    'auth.logout_sucesso'      => 'Você saiu do sistema.',
    'auth.conta_inativa'       => 'Sua conta está inativa. Entre em contato com o suporte.',
    'auth.token_invalido'      => 'Token inválido ou expirado.',
    'auth.senha_redefinida'    => 'Senha redefinida com sucesso.',
    'auth.email_enviado'       => 'E-mail de redefinição enviado.',
    'auth.2fa_titulo'          => 'Autenticação em Dois Fatores',
    'auth.2fa_codigo'          => 'Código de verificação',
    'auth.2fa_invalido'        => 'Código inválido.',
    'auth.primeiro_acesso'     => 'Primeiro Acesso',
    'auth.criar_superadmin'    => 'Criar Super Administrador',

    // Sidebar Equipe
    'sidebar.dashboard'        => 'Dashboard',
    'sidebar.clientes'         => 'Clientes',
    'sidebar.parceiros'        => 'Parceiros',
    'sidebar.demandas'         => 'Demandas',
    'sidebar.oportunidades'    => 'Oportunidades',
    'sidebar.propostas'        => 'Propostas',
    'sidebar.contratos'        => 'Contratos',
    'sidebar.comissoes'        => 'Comissões',
    'sidebar.qualificacao'     => 'Qualificação',
    'sidebar.vetriks'          => 'Vetriks',
    'sidebar.crm'              => 'CRM',
    'sidebar.tarefas'          => 'Tarefas',
    'sidebar.mensagens'        => 'Mensagens',
    'sidebar.relatorios'       => 'Relatórios',
    'sidebar.configuracoes'    => 'Configurações',
    'sidebar.usuarios'         => 'Usuários',
    'sidebar.permissoes'       => 'Permissões',
    'sidebar.logs'             => 'Logs',
    'sidebar.jobs'             => 'Jobs',
    'sidebar.minha_conta'      => 'Minha Conta',

    // Sidebar Cliente
    'sidebar_cli.dashboard'    => 'Dashboard',
    'sidebar_cli.demandas'     => 'Minhas Demandas',
    'sidebar_cli.propostas'    => 'Propostas Recebidas',
    'sidebar_cli.mensagens'    => 'Mensagens',
    'sidebar_cli.minha_conta'  => 'Minha Conta',

    // Sidebar Parceiro
    'sidebar_par.dashboard'    => 'Dashboard',
    'sidebar_par.oportunidades'=> 'Oportunidades',
    'sidebar_par.propostas'    => 'Minhas Propostas',
    'sidebar_par.comissoes'    => 'Comissões',
    'sidebar_par.perfil'       => 'Meu Perfil',
    'sidebar_par.mensagens'    => 'Mensagens',
    'sidebar_par.minha_conta'  => 'Minha Conta',

    // Status Demanda
    'status.novo'                  => 'Novo',
    'status.em_triagem'            => 'Em Triagem',
    'status.em_estruturacao'       => 'Em Estruturação',
    'status.pronto_repasse'        => 'Pronto para Repasse',
    'status.distribuido'           => 'Distribuído',
    'status.aguardando_respostas'  => 'Aguardando Respostas',
    'status.recebendo_propostas'   => 'Recebendo Propostas',
    'status.em_curadoria'          => 'Em Curadoria',
    'status.apresentado_cliente'   => 'Apresentado ao Cliente',
    'status.em_negociacao'         => 'Em Negociação',
    'status.contrato_formalizacao' => 'Contrato em Formalização',
    'status.fechado_ganho'         => 'Fechado — Ganho',
    'status.fechado_perda'         => 'Fechado — Perda',
    'status.pausado'               => 'Pausado',
    'status.cancelado'             => 'Cancelado',

    // Status Parceiro
    'status_par.cadastrado'        => 'Cadastrado',
    'status_par.pendente_analise'  => 'Pendente de Análise',
    'status_par.em_qualificacao'   => 'Em Qualificação',
    'status_par.aprovado'          => 'Aprovado',
    'status_par.vetriks_ativo'     => 'Vetriks Ativo',
    'status_par.reprovado'         => 'Reprovado',
    'status_par.suspenso'          => 'Suspenso',
    'status_par.inativo'           => 'Inativo',

    // Status Proposta
    'status_prop.rascunho'         => 'Rascunho',
    'status_prop.enviada'          => 'Enviada',
    'status_prop.em_analise'       => 'Em Análise',
    'status_prop.shortlist'        => 'Shortlist',
    'status_prop.descartada'       => 'Descartada',
    'status_prop.selecionada'      => 'Selecionada',
    'status_prop.convertida'       => 'Convertida',
    'status_prop.perdida'          => 'Perdida',

    // Status Comissão
    'status_com.prevista'              => 'Prevista',
    'status_com.aguardando_confirmacao'=> 'Aguardando Confirmação',
    'status_com.confirmada'            => 'Confirmada',
    'status_com.faturada'              => 'Faturada',
    'status_com.recebida'              => 'Recebida',
    'status_com.atrasada'              => 'Atrasada',
    'status_com.cancelada'             => 'Cancelada',

    // Erros
    'erro.pagina_nao_encontrada' => 'Página não encontrada.',
    'erro.sem_permissao'         => 'Você não tem permissão para acessar este recurso.',
    'erro.interno'               => 'Erro interno do servidor.',
    'erro.csrf'                  => 'Token de segurança inválido. Recarregue a página.',
    'erro.rate_limit'            => 'Muitas requisições. Tente novamente em breve.',
    'erro.validacao'             => 'Verifique os campos e tente novamente.',

    // Contato
    'contato.titulo'       => 'Entre em Contato',
    'contato.nome'         => 'Seu nome',
    'contato.email'        => 'Seu e-mail',
    'contato.telefone'     => 'Telefone',
    'contato.assunto'      => 'Assunto',
    'contato.mensagem'     => 'Mensagem',
    'contato.enviar'       => 'Enviar Mensagem',
    'contato.sucesso'      => 'Mensagem enviada com sucesso. Entraremos em contato em breve.',

    // Formulário Demanda
    'demanda.titulo'           => 'Abrir Demanda',
    'demanda.dados_pessoais'   => 'Dados Pessoais',
    'demanda.dados_obra'       => 'Dados da Obra',
    'demanda.uploads'          => 'Documentos e Projetos',
    'demanda.revisao'          => 'Revisão',
    'demanda.tipo_obra'        => 'Tipo de Obra',
    'demanda.localizacao'      => 'Localização',
    'demanda.metragem'         => 'Metragem (m²)',
    'demanda.fase_atual'       => 'Fase Atual',
    'demanda.prazo_desejado'   => 'Prazo Desejado',
    'demanda.orcamento'        => 'Orçamento Estimado',
    'demanda.descricao'        => 'Descrição Detalhada',
    'demanda.urgencia'         => 'Urgência',
    'demanda.tem_projeto'      => 'Já possui projeto?',
    'demanda.tem_arquiteto'    => 'Já possui arquiteto?',
    'demanda.multiplas_prop'   => 'Deseja múltiplas propostas?',
    'demanda.observacoes'      => 'Observações Adicionais',
    'demanda.sucesso'          => 'Demanda registrada com sucesso. Entraremos em contato em breve.',

    // Formulário Parceiro
    'parceiro.titulo'          => 'Seja Parceiro',
    'parceiro.dados_empresa'   => 'Dados da Empresa',
    'parceiro.dados_prof'      => 'Dados Profissionais',
    'parceiro.qualificacao'    => 'Qualificação',
    'parceiro.tipo'            => 'Tipo de Parceiro',
    'parceiro.especialidades'  => 'Especialidades',
    'parceiro.areas_atuacao'   => 'Áreas de Atuação',
    'parceiro.cidades'         => 'Cidades Atendidas',
    'parceiro.ticket_medio'    => 'Ticket Médio',
    'parceiro.equipe_propria'  => 'Equipe Própria?',
    'parceiro.tempo_mercado'   => 'Tempo de Mercado (anos)',
    'parceiro.portfolio'       => 'Portfólio',
    'parceiro.certificacoes'   => 'Certificações',
    'parceiro.aceita_repasse'  => 'Aceita repasse?',
    'parceiro.sucesso'         => 'Cadastro realizado com sucesso. Analisaremos seu perfil em breve.',

    // Cookies / LGPD
    'cookies.titulo'           => 'Política de Cookies',
    'cookies.mensagem'         => 'Utilizamos cookies para melhorar sua experiência. Ao continuar navegando, você concorda com nossa política de cookies.',
    'cookies.aceitar'          => 'Aceitar Todos',
    'cookies.rejeitar'         => 'Rejeitar Opcionais',
    'cookies.configurar'       => 'Configurar',
    'cookies.necessarios'      => 'Necessários',
    'cookies.analytics'        => 'Analytics',
    'cookies.marketing'        => 'Marketing',
    'cookies.preferencias'     => 'Preferências',
    'cookies.salvar'           => 'Salvar Preferências',

    // Chatbot
    'chatbot.titulo'           => 'Olá! Como posso ajudar?',
    'chatbot.opcao1'           => 'O que é a Lexus?',
    'chatbot.opcao2'           => 'Como funciona?',
    'chatbot.opcao3'           => 'Como abrir uma demanda?',
    'chatbot.opcao4'           => 'Como ser parceiro?',
    'chatbot.opcao5'           => 'O que é o Selo Vetriks?',
    'chatbot.opcao6'           => 'Falar com atendimento',
    'chatbot.voltar'           => 'Voltar ao menu',

    // Dashboard
    'dash.novas_demandas'      => 'Novas Demandas',
    'dash.oportunidades_ativas'=> 'Oportunidades Ativas',
    'dash.propostas_andamento' => 'Propostas em Andamento',
    'dash.fechamentos'         => 'Fechamentos',
    'dash.taxa_conversao'      => 'Taxa de Conversão',
    'dash.parceiros_ativos'    => 'Parceiros Ativos',
    'dash.clientes_ativos'     => 'Clientes Ativos',
    'dash.comissoes_previstas' => 'Comissões Previstas',
    'dash.comissoes_recebidas' => 'Comissões Recebidas',

    // Páginas institucionais
    'pagina.como_funciona'     => 'Como Funciona',
    'pagina.para_clientes'     => 'Para Clientes',
    'pagina.para_parceiros'    => 'Para Parceiros',
    'pagina.vetriks'           => 'Selo Vetriks',
    'pagina.sobre'             => 'Sobre a Lexus',
    'pagina.contato'           => 'Contato',
    'pagina.termos'            => 'Termos de Uso',
    'pagina.privacidade'       => 'Política de Privacidade',
    'pagina.status'            => 'Status do Sistema',
    'pagina.changelog'         => 'Changelog',

    // Configurações
    'config.branding'          => 'Branding',
    'config.contatos'          => 'Contatos Institucionais',
    'config.smtp'              => 'E-mail SMTP',
    'config.seo'               => 'SEO',
    'config.lgpd'              => 'LGPD',
    'config.notificacoes'      => 'Notificações',
    'config.matching'          => 'Regras de Matching',
    'config.comissao'          => 'Regras de Comissão',
    'config.distribuicao'      => 'Regras de Distribuição',
    'config.vetriks_criterios' => 'Critérios Vetriks',
    'config.billing'           => 'Billing',
    'config.stripe'            => 'Stripe',
    'config.asaas'             => 'Asaas',
    'config.webhooks'          => 'Webhooks',
    'config.idioma'            => 'Idioma e Localização',
    'config.chatbot'           => 'Chatbot',

    // Configurações — descrições
    'config.subtitulo'         => 'Gerencie todas as configurações do sistema',
    'config.branding_desc'     => 'Logo, nome, cores e identidade visual',
    'config.smtp_desc'         => 'Configurações de envio de e-mail',
    'config.seo_desc'          => 'Meta tags, Open Graph e indexação',
    'config.cobranca'          => 'Cobrança',
    'config.cobranca_desc'     => 'Stripe, Asaas, planos e webhooks',
    'config.notificacoes_desc' => 'E-mails, alertas e canais de notificação',
    'config.integracao'        => 'Integrações',
    'config.integracao_desc'   => 'APIs externas e webhooks',
    'config.seguranca'         => 'Segurança',
    'config.seguranca_desc'    => 'Senhas, 2FA, rate limit e LGPD',
    'config.geral'             => 'Geral',
    'config.geral_desc'        => 'Idioma, moeda, timezone e preferências',
    'config.legal'             => 'Textos Legais',
    'config.legal_desc'        => 'Termos de uso e política de privacidade',
    'config.matching_desc'     => 'Regras de matching entre demandas e parceiros',
    'config.comissao_desc'     => 'Percentuais e regras de comissão',
    'config.vetriks_desc'      => 'Critérios de qualificação Vetriks',
    'config.chatbot_desc'      => 'Mensagens e opções do chatbot',

    // Minha Conta (equipe)
    'conta.titulo'             => 'Minha Conta',
    'conta.dados_pessoais'     => 'Dados Pessoais',
    'conta.alterar_senha'      => 'Alterar Senha',
    'conta.senha_atual'        => 'Senha Atual',
    'conta.nova_senha'         => 'Nova Senha',
    'conta.confirmar_nova'     => 'Confirmar Nova Senha',
    'conta.manter_vazia'       => 'Deixe em branco para manter a senha atual.',
];
